name: Java Workflow Example - Build, Test and Deploy

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          architecture: x64
          # When using Maven Central Repository
          # server-id: ossrh
          # server-username: MAVEN_USERNAME
          # server-password: MAVEN_PASSWORD

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Maven Test
        run: mvn test

      - run: mkdir coverage-report && cp -r target/site/jacoco/* coverage-report

      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1

      - uses: actions/upload-artifact@v2
        with:
          name: Test Coverage Report
          path: coverage-report

  deploy:
    name: Deploy to Github Repository
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Maven Build and Publish
        run: mvn -B deploy
        env:
          # GITHUB_TOKEN is provided by default in the repo with read/write access to Github Packages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # When using Maven Central Repository
          # MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          # MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

      - run: mkdir dist && cp target/*.jar dist

      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: dist
