name: DevSecOps CI

on:
  push:
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    name: Check OWASP Dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Maven Test
        run: mvn org.owasp:dependency-check-maven:check

      - run: mkdir owasp-dependency-check-report && cp target/dependency-check-report.html owasp-dependency-check-report

      - uses: actions/upload-artifact@v2
        with:
          name: OWASP Dependency Check Report
          path: owasp-dependency-check-report
