name: "PR Status Check"

on:
  pull_request:
    branches: [master]

jobs:
  check-build-test:
    name: "Check build and test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Maven Test
        run: mvn test

      - run: mkdir coverage-report && cp -r target/site/jacoco/* coverage-report

      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1

      - uses: actions/upload-artifact@v2
        with:
          name: Test Coverage Report
          path: coverage-report
